Tweak configure to support apachever=2.2.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,7 +14,7 @@ if [ $DIR = '.' ]; then
 fi
 
 usage() {
-  echo "usage: $ME [--apxs=/path/to/apxs] [--apachever=<1|2>] [--debug]"
+  echo "usage: $ME [--apxs=/path/to/apxs] [--apachever=<1|2|2.2>] [--debug]"
 }
 die() {
   echo $*
@@ -62,8 +62,15 @@ test -x $APXS || die "Error: missing apxs '$APXS' (use --apxs=/path/to/apxs)"
 # Get Apache version
 if [ -z "$VERSION" ]; then
   HTTPD=`$APXS -q SBINDIR`/`$APXS -q TARGET`
-  test -x $HTTPD || die "Error: cannot determine apache version (use --apachever=<1|2>)"
-  VERSION=`$HTTPD -v | head -1 | sed -e 's/.*Apache\///' -e 's/\..*//'`
+  test -x $HTTPD || die "Error: cannot determine apache version (use --apachever=<1|2|2.2>)"
+  VERSION=`$HTTPD -v | head -1 | sed -e 's/.*Apache\///' -e 's/^\([0-9]\.[0-9]\+\).*/\1/'`
+fi
+# Standardise
+test $VERSION = '2.0' && VERSION=2
+test $VERSION = '20'  && VERSION=2
+test $VERSION = '22'  && VERSION=2.2
+if [ $VERSION != '1' -a $VERSION != '2' -a $VERSION != '2.2' ]; then
+  die "Error: apache version '$VERSION' not supported"
 fi
 
 # Generate Makedefs
@@ -78,7 +85,7 @@ echo >> Makedefs
 echo "VERSION = $VERSION" >> Makedefs
 echo "APXS = $APXS" >> Makedefs
 test -n "$DEBUG" && echo "CFLAGS += $DEBUG" >> Makedefs
-if [ "$VERSION" -lt 2 ]; then
+if [ "$VERSION" = "1" ]; then
   echo "CFLAGS += -DAPACHE13" >> Makedefs
   echo "TARGET = mod_auth_tkt.so" >> Makedefs
 else
